version: '2'

services:
   web-lets:
     image: registry.spin.nersc.gov/das/letsencrypt:latest
     restart: always
     volumes:
       - web.mydomain-net:/etc/letsencrypt/
     environment:
       LE_DOMAIN: web.mydomain.net
       LE_EMAIL: user@mydomain.net
       PROXY: web-app:80
     labels:
       io.rancher.container.pull_image: always

   web-app:
     image: nginx
     restart: always
     labels:
       io.rancher.container.pull_image: always

volumes:
    web.mydomain-net:
        driver: rancher-nfs
        external: true


